### ISSUE TITLE
При попытке запуска автотестов русские символы кодируются некорректно

### ISSUE THREAD

**Issue by marpluto** [marpluto/qa.diploma#1]
# Описание
При попытке запуска автотестов в IntelliJ IDEA русские символы кодируются некорректно, из-за чего все автотесты падают.

# Шаги воспроизведения
1. Отрыть [проект](https://github.com/marpluto/qa.diploma) в IntelliJ IDEA
2. Запустить программу Docker
3. Используя плагин Docker в IntelliJ IDEA запустить контейнеры `mysql` и `nodejs`
4. Используя плагин Database Navigator для IntelliJ IDEA настроить подключение к базе данных (изображение 1)
5. В терминале IntelliJ IDEA набрать команду `java -jar ./artifacts/aqa-shop.jar -P:jdbc url=jdbc:mysql://localhost:3306/app`, чтобы запустить SUT на базе mySQL
6. Можно перейти в браузере по адресу `http://localhost:8080`, убедиться, что страница сервиса открывается
7. В терминале IntelliJ IDEA набрать команду `./gradlew clean test --info` для запуска автотестов
8. Увидеть отчет о запуске тестов
<details><summary>Уточнение</summary>
На данный момент все автотесты, кроме одного, закомментированы для удобства
</details> 

*Ожидаемый результат:* автотест отрабатывает скрипт до конца, в консоли виден отчет о тестировании
*Фактический результат:* автотест падает на шаге скрипта, когда необходимо проверить на видимость заголовок страницы, в отчете видно, что тест обрушился из-за неправильного отображения русских символов при прогоне теста (изображение 2)

# Логи
<details><summary>Логи сборки в IntelliJ IDEA</summary>
<p>

```java
CreditGateTest > shouldSuccessfullyBuyWithApprovedCard() FAILED
    Element not found {h3.findBy(exact text "╨Ю╨┐╨╗╨░╤В╨░ ╨┐╨╛ ╨║╨░╤А╤В╨╡")}
    Expected: visible
    Screenshot: file:/C:/Users/╧юы№чютрЄхы№/IdeaProjects/qa.diploma/build/reports/tests/1700284025635.0.png
    Page source: file:/C:/Users/╧юы№чютрЄхы№/IdeaProjects/qa.diploma/build/reports/tests/1700284025635.0.html
    Timeout: 4 s.
    Caused by: NoSuchElementException: Cannot locate an element h3.findBy(exact text "╨Ю╨┐╨╗╨░╤В╨░ ╨┐╨╛ ╨║╨░╤А╤В╨╡")
        at app//com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:91)
        at app//com.codeborne.selenide.impl.WebElementSource.handleError(WebElementSource.java:143)
        at app//com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:127)
        at app//com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:104)
        at app//com.codeborne.selenide.commands.Should.execute(Should.java:30)
        at app//com.codeborne.selenide.commands.Should.execute(Should.java:14)
        at app//com.codeborne.selenide.commands.Commands.execute(Commands.java:163)
        at app//com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:132)
        at app//com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:84)
        at app//com.sun.proxy.$Proxy19.shouldBe(Unknown Source)
        at app//ru.netology.pages.ChoosingPaymentMethod.<init>(ChoosingPaymentMethod.java:16)
        at app//ru.netology.test.CreditGateTest.shouldSuccessfullyBuyWithApprovedCard(CreditGateTest.java:38)

        Caused by:
        org.openqa.selenium.NoSuchElementException: Cannot locate an element h3.findBy(exact text "╨Ю╨┐╨╗╨░╤В╨░ ╨┐╨╛ ╨║╨░╤А╤В╨╡")
        For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
        Build info: version: '4.11.0', revision: '040bc5406b'
        System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.0.1'
        Driver info: driver.version: unknown
            at app//com.codeborne.selenide.impl.CollectionElementByCondition.getWebElement(CollectionElementByCondition.java:55)
            at app//com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:116)
            ... 9 more

1 test completed, 1 failed

``` 

</p>
</details> 

# Скриншоты
### Изображение 1
<img width="922" alt="Screenshot at Nov 16 18-47-27" src="https://github.com/marpluto/qa.diploma/assets/120597031/b4d8b13d-4464-4584-8a39-52351493b7a0">

### Изображение 2
<img width="536" alt="Screenshot at Nov 13 22-48-09" src="https://github.com/marpluto/qa.diploma/assets/120597031/681bd30a-1511-4ca9-8414-59e500ec29b7">

# Предпринятые попытки решения проблемы
1. Проверка настроек File Encodings в IntelliJ IDEA. Выставлены и проверены значения: <Default>, UTF-8, windows-1251. Ни при одном из вариантов итог прогона автотестов не менялся.
<img width="763" alt="Screenshot at Nov 13 22-50-17" src="https://github.com/marpluto/qa.diploma/assets/120597031/e143724b-2219-434d-b486-9eb6635cc980">

2. Через Edit Custom VM Options в меню Help была вручную прописана кодировка UTF-8
<img width="840" alt="Screenshot at Nov 13 22-49-40" src="https://github.com/marpluto/qa.diploma/assets/120597031/60aebd1f-826a-49be-a034-b1b7112a76de">

3.  Также была попытка прописать кодировку UTF-8 в buld.gradle
<img width="854" alt="Screenshot at Nov 16 19-06-31" src="https://github.com/marpluto/qa.diploma/assets/120597031/00a8994f-c416-46d3-b3cd-fe395b309235">

#### Ни один из опробованных вариантов не изменил фактического результата прогона автотестов

# Окружение
* **Операционная система:** Windows 10 x64
* **IDEA:** IntelliJ IDEA 2023.2.4 (Community Edition)
* **Java:** OpenJDK 11
* **Сборка:** Gradle
* **Test:** junit-jupiter, selenide

**Comment by marpluto** [comment]
Помогла ручная переустановка и настройка Java
