### ISSUE TITLE
При подключении проекта к БД PostgreSQL в приложении отсутствуют таблицы

### ISSUE THREAD

**Issue by marpluto** [marpluto/qa.diploma#8]
# Описание
При подключении проекта к СУБД PostgreSQL в приложении отсутствуют таблицы, из-за чего становится невозможным дальнейшее тестирование.

# Шаги воспроизведения
1. Отрыть [проект](https://github.com/marpluto/qa.diploma) в IntelliJ IDEA
2. Запустить программу Docker
3. В консоли набрать команду `docker-compose up`
4. Запустить программу DBeaver, настроить подключение к БД PostgreSQL, в качестве данных для подключения указать: Database `app`, User `app`, Password `pass`, Port `5432`
5. В меню посмотреть содержимое вкладки "Таблицы"

*Ожидаемый результат:* во вкладке Таблицы отображаются три таблицы: `credit_request_entity`, `order_entity` и `payment_entity`.
*Фактический результат:* во вкладке Таблицы пусто.

<details><summary>Примечание</summary>
Тот же результат получается при подключении БД через плагин Database Navigator для IntelliJ IDEA
</details> 

# Логи
<details><summary>Логи сборки в IntelliJ IDEA при попытке запустить автотест</summary>
<p>

```java
Initialized native services in: C:\Users\Пользователь\.gradle\native
Initialized jansi services in: C:\Users\Пользователь\.gradle\native
The client will now receive all logging from the daemon (pid: 21072). The daemon log file: C:\Users\Пользователь\.gradle\daemon\7.5.1\daemon-21072.out.log
Starting 8th build in daemon [uptime: 19 mins 54.471 secs, performance: 100%, non-heap usage: 37% of 256 MiB]                                             
Using 4 worker leases.                                                                                                                                    
Now considering [C:\Users\Пользователь\IdeaProjects\qa.diploma] as hierarchies to watch                                                                   
Watching the file system is configured to be enabled if available                                                                                         
File system watching is active
Starting Build
Settings evaluated using settings file 'C:\Users\Пользователь\IdeaProjects\qa.diploma\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\Пользователь\IdeaProjects\qa.diploma\build.gradle'.
Included projects: [root project 'qa.diploma']

> Configure project :
Evaluating root project 'qa.diploma' using build file 'C:\Users\Пользователь\IdeaProjects\qa.diploma\build.gradle'.
All projects evaluated.
Task name matched 'clean'
Task name matched 'test'
Selected primary task 'clean' from project :
Selected primary task 'test' from project :
Tasks to be executed: [task ':clean', task ':compileJava', task ':processResources', task ':classes', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test']
Tasks that were excluded: []
Resolve mutations for :clean (Thread[Execution worker,5,main]) started.
Resolve mutations for :clean (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
:clean (Thread[included builds,5,main]) started.
destroyer locations for task group 0 (Thread[Execution worker,5,main]) started.
destroyer locations for task group 0 (Thread[Execution worker,5,main]) completed. Took 0.0 secs.

> Task :clean
Caching disabled for task ':clean' because:
  Build cache is disabled
Task ':clean' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :compileJava (Thread[Execution worker,5,main]) started.
:clean (Thread[included builds,5,main]) completed. Took 0.043 secs.
Resolve mutations for :compileJava (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
:compileJava (Thread[Execution worker,5,main]) started.

> Task :compileJava NO-SOURCE
Skipping task ':compileJava' as it has no source files and no previous output files.
:compileJava (Thread[Execution worker,5,main]) completed. Took 0.001 secs.
Resolve mutations for :processResources (Thread[Execution worker,5,main]) started.
Resolve mutations for :processResources (Thread[Execution worker,5,main]) completed. Took 0.001 secs.
:processResources (Thread[Execution worker,5,main]) started.

> Task :processResources NO-SOURCE
Skipping task ':processResources' as it has no source files and no previous output files.
:processResources (Thread[Execution worker,5,main]) completed. Took 0.005 secs.
Resolve mutations for :classes (Thread[Execution worker,5,main]) started.
Resolve mutations for :classes (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
:classes (Thread[Execution worker,5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
Resolve mutations for :compileTestJava (Thread[Execution worker,5,main]) started.
Resolve mutations for :compileTestJava (Thread[Execution worker,5,main]) completed. Took 0.0 secs.
:compileTestJava (Thread[Execution worker,5,main]) started.

> Task :compileTestJava
allure-gradle: added dependency io.qameta.allure:allure-junit5:2.20.1 to apiElements scope of org.junit.jupiter:junit-jupiter-api:5.8.1
Caching disabled for task ':compileTestJava' because:
  Build cache is disabled
Task ':compileTestJava' is not up-to-date because:
  Output property 'destinationDirectory' file C:\Users\Пользователь\IdeaProjects\qa.diploma\build\classes\java\test has been removed.
  Output property 'destinationDirectory' file C:\Users\Пользователь\IdeaProjects\qa.diploma\build\classes\java\test\ru has been removed.
  Output property 'destinationDirectory' file C:\Users\Пользователь\IdeaProjects\qa.diploma\build\classes\java\test\ru\netology has been removed.
The input changes require a full rebuild for incremental task ':compileTestJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain 'C:\Program Files\Java\jdk-11'.
Compiling with JDK Java compiler API.
Class dependency analysis for incremental compilation took 0.01 secs.
Created classpath snapshot for incremental compilation in 0.012 secs.
Resolve mutations for :processTestResources (Thread[Execution worker Thread 3,5,main]) started.
:compileTestJava (Thread[Execution worker,5,main]) completed. Took 1.504 secs.
:processTestResources (Thread[Execution worker Thread 2,5,main]) started.
Resolve mutations for :processTestResources (Thread[Execution worker Thread 3,5,main]) completed. Took 0.0 secs.

> Task :processTestResources NO-SOURCE
Skipping task ':processTestResources' as it has no source files and no previous output files.
Resolve mutations for :testClasses (Thread[Execution worker Thread 3,5,main]) started.
:processTestResources (Thread[Execution worker Thread 2,5,main]) completed. Took 0.001 secs.
Resolve mutations for :testClasses (Thread[Execution worker Thread 3,5,main]) completed. Took 0.0 secs.
:testClasses (Thread[Execution worker Thread 2,5,main]) started.

> Task :testClasses
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[Execution worker Thread 2,5,main]) completed. Took 0.0 secs.
Resolve mutations for :test (Thread[Execution worker Thread 3,5,main]) started.
Resolve mutations for :test (Thread[Execution worker Thread 3,5,main]) completed. Took 0.0 secs.
:test (Thread[Execution worker Thread 3,5,main]) started.
producer locations for task group 1 (Thread[Execution worker Thread 2,5,main]) started.
producer locations for task group 1 (Thread[Execution worker Thread 2,5,main]) completed. Took 0.0 secs.
Gradle Test Executor 7 started executing tests.

> Task :test
file or directory 'C:\Users\Пользователь\IdeaProjects\qa.diploma\build\allure-results', not found
allure-gradle: added dependency io.qameta.allure:allure-junit5:2.20.1 to runtimeElements scope of org.junit.jupiter:junit-jupiter-api:5.8.1
allure-gradle: added dependency io.qameta.allure:allure-junit5:2.20.1 to runtimeElements scope of org.junit.jupiter:junit-jupiter-api:5.8.2
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  Task has failed previously.
Starting process 'Gradle Test Executor 7'. Working directory: C:\Users\Пользователь\IdeaProjects\qa.diploma Command: C:\Program Files\Java\jdk-11\bin\java.exe -Dallure.results.directory=C:\Users\Пользователь\IdeaProjects\qa.dipl
oma\build\allure-results -Ddb.url=jdbc:postgresql://localhost:5432/app -Djunit.jupiter.extensions.autodetection.enabled=true -Dorg.gradle.internal.worker.tmpdir=C:\Users\Пользователь\IdeaProjects\qa.diploma\build\tmp\test\work -
Dorg.gradle.native=false -Dselenide.headless -javaagent:C:\Users\Пользователь\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjweaver\1.9.9.1\dcd2703279a94ad909fa3f3d08671cb0f2dabf7\aspectjweaver-1.9.9.1.jar @C:\Users\Польз
ователь\.gradle\.tmp\gradle-worker-classpath521164074174530396txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=RU -Duser.language=ru -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Exe
cutor 7'
Successfully started process 'Gradle Test Executor 7'

Gradle Test Executor 7 STANDARD_ERROR
    SLF4J: No SLF4J providers were found.
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

CreditGateTest > shouldSuccessfullyBuyWithApprovedCard() STANDARD_ERROR
    нояб. 19, 2023 8:16:09 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
    WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 115

Gradle Test Executor 7 finished executing tests.

> Task :test

CreditGateTest > shouldSuccessfullyBuyWithApprovedCard() FAILED
    java.sql.SQLException: ERROR: relation "credit_request_entity" does not exist
      Позиция: 20 Query: SELECT status FROM credit_request_entity; Parameters: []
        at app//org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
        at app//org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:391)
        at app//org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at app//ru.netology.data.SQLHelper.getData(SQLHelper.java:55)
        at app//ru.netology.data.SQLHelper.getCreditRequestStatus(SQLHelper.java:37)
        at app//ru.netology.test.CreditGateTest.shouldSuccessfullyBuyWithApprovedCard(CreditGateTest.java:42)

1 test completed, 1 failed
Finished generating test XML results (0.032 secs) into: C:\Users\Пользователь\IdeaProjects\qa.diploma\build\test-results\test
Generating HTML test report...
Finished generating test html results (0.078 secs) into: C:\Users\Пользователь\IdeaProjects\qa.diploma\build\reports\tests\test

> Task :test FAILED
:test (Thread[Execution worker,5,main]) completed. Took 18.791 secs.

FAILURE: Build failed with an exception.


``` 

</p>
</details> 

# Скриншоты
### Настройки соединения
![Screenshot_20](https://github.com/marpluto/qa.diploma/assets/120597031/0ee057ff-4108-4a41-8eac-3941c1415e07)

### Фактический результат
![Screenshot_14](https://github.com/marpluto/qa.diploma/assets/120597031/61a9856e-3859-418f-af2a-8e94c5d16c35)

### Подключение проекта к БД MySQL
![Screenshot_15](https://github.com/marpluto/qa.diploma/assets/120597031/f8d38715-98c2-4375-bfde-8cf31ac9383a)

### При подключении к PostgreSQL в консоли через exec
![Screenshot_18](https://github.com/marpluto/qa.diploma/assets/120597031/26880dfe-10c1-460c-a492-c76ce07f30a4)

### При этом UI-тест проходит успешно
![Screenshot_19](https://github.com/marpluto/qa.diploma/assets/120597031/228a827a-07e3-4251-875a-ddb5738499da)

# Окружение
* **Операционная система:** Windows 10 x64
* **IDEA:** IntelliJ IDEA 2023.2.4 (Community Edition)
* **Java:** OpenJDK 11
* **Сборка:** Gradle
* **Test:** junit-jupiter, selenide
* **DBeaver:** 23.2.4

**Comment by marpluto** [comment]
Ошибка происходила из-за того, что не была проведена должная настройка файла application.properties
